# Accessing Elements of 2D Array

# Time Complexity : O(1)
# Space Complexity : O(1)

In [1]:
import numpy as np

# Create a 2D array

twoDArray = np.array([[11,15,10,6],[10,14,11,5],[12,17,12,8],[15,18,14,9]])
print(twoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [ ]:
def accessElements(array, rowIndex, colIndex):
    if rowIndex >= len(array) and colIndex >= len(array[0]):   # ---> O(1)
        print("Incorrect Index")    # ---> O(1)
    else:           
        print(array[rowIndex][colIndex])   # ---> O(1)

accessElements(twoDArray, 1, 2)

11


In [4]:
accessElements(twoDArray, 2, 3)

8


In [5]:
accessElements(twoDArray, 3, 3)

9
