# Traversal 

# Time Complexity : O(n^2)
# Space Complexity : O(1)

In [1]:
import numpy as np

# Create a 2D array

twoDArray = np.array([[11,15,10,6],[10,14,11,5],[12,17,12,8],[15,18,14,9]])
print(twoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [ ]:
def traverseTDArray(array):
    for i in range(len(array)):          # ----> O(mn)
        for j in range(len(array[0])):       # ----> O(n)
            print(array[i][j])     # ----> O(1)

traverseTDArray(twoDArray)   

11
15
10
6
10
14
11
5
12
17
12
8
15
18
14
9
