# Searching in 2D Array

# Time Complexity : O(mn)
# Space Complexity : O(1)

In [1]:
import numpy as np

# Create a 2D array

twoDArray = np.array([[11,15,10,6],[10,14,11,5],[12,17,12,8],[15,18,14,9]])
print(twoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [ ]:
def searchTDArray(array, value):
    for i in range(len(array)):     # -----> O(mn)
        for j in range(len(array[0])):  # -----> O(n)
            if array[i][j] == value:    # -----> O(1)
                return "The value is located at index " +str(i)+" "+str(j)
            
    return "The element is not found"

print(searchTDArray(twoDArray, 14))

The value is located at index 1 1


In [4]:
print(searchTDArray(twoDArray, 9))

The value is located at index 3 3


In [5]:
print(searchTDArray(twoDArray, 54))

The element is not found
