# Deletion : In the deletion of numpy each rows moves one step upwards.

# Time Complexity : O(mn)

In [1]:
import numpy as np

# Create a 2D array

twoDArray = np.array([[11,15,10,6],[10,14,11,5],[12,17,12,8],[15,18,14,9]])
print(twoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [2]:
newTDArray = np.delete(twoDArray, 0, axis= 0)
print(newTDArray)

[[10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [3]:
newTDArray = np.delete(twoDArray, 1, axis= 1)
print(newTDArray)

[[11 10  6]
 [10 11  5]
 [12 12  8]
 [15 14  9]]
