# 2D Array

# This are the temperature

- Day 1 - 11, 15, 10, 6
- Day 2 - 10, 14, 11, 5
- Day 3 - 12, 17, 12, 8
- Day 4 - 15, 18, 14, 9

# Time Complexity : O(m*n) m number of columns and n number of rows.
# Space Complexity : O(nm)

In [1]:
import numpy as np

# Create a 2D array

twoDArray = np.array([[11,15,10,6],[10,14,11,5],[12,17,12,8],[15,18,14,9]])
print(twoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
