# Insertion in 2D array

# Time Complexity : O(mn)

In [1]:
import numpy as np

# Create a 2D array

twoDArray = np.array([[11,15,10,6],[10,14,11,5],[12,17,12,8],[15,18,14,9]])
print(twoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [2]:
newTwoDArray = np.insert(twoDArray, 0, [[1,2,3,4]], axis=1)  # axis = 1 column and axis = 0 row.
print(newTwoDArray)

[[ 1 11 15 10  6]
 [ 2 10 14 11  5]
 [ 3 12 17 12  8]
 [ 4 15 18 14  9]]


In [3]:
newTwoDArray = np.insert(twoDArray, 0, [[1,2,3,4]], axis=0)  # axis = 1 column and axis = 0 row.
print(newTwoDArray)

[[ 1  2  3  4]
 [11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [4]:
newTwoDArray = np.insert(twoDArray, 1, [[1,2,3,4]], axis=0)  # axis = 1 column and axis = 0 row.
print(newTwoDArray)

[[11 15 10  6]
 [ 1  2  3  4]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [5]:
newTwoDArray = np.append(twoDArray, [[1,2,3,4]], axis=0)  # axis = 1 column and axis = 0 row.
print(newTwoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]
 [ 1  2  3  4]]
